version: '3'
services:
  plugin_store:
    build: .
    container_name: plugin_store
    environment:
        - DB_PATH=/app/.database/plugin_store_new.db
        - ANNOUNCEMENT_WEBHOOK
        - SUBMIT_AUTH_KEY=deadbeef
        - B2_APP_KEY_ID
        - B2_APP_KEY
        - B2_BUCKET_ID
    volumes:
        - .:/app
    restart: unless-stopped
    ports:
        - "5566:5566"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 5566

  redis_db:
    image: redis:latest
    restart: unless-stopped
    ports:
        - "6379:6379"
    environment:
        - REDIS_PORT=6379
